---
sudo: required

language: go
service:
  - docker

go:
  - "1.10.x"

go_import_path: github.com/ligato/crd-example

before_install:
  - ./.travis/update-docker.sh

before_script:
  - sudo mount --make-rshared /
  - sudo mount --make-rshared /sys
  - sudo mount --make-rshared /var/run

script:
  - make yamllint
  - make all
