// Copyright (c) 2018 Cisco and/or its affiliates.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at:
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	crdexampleiov1 "github.com/ligato/crd-example/pkg/apis/crdexample.io/v1"
	versioned "github.com/ligato/crd-example/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ligato/crd-example/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/ligato/crd-example/pkg/client/listers/crdexample.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CrdExampleEmbedInformer provides access to a shared informer and lister for
// CrdExampleEmbeds.
type CrdExampleEmbedInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CrdExampleEmbedLister
}

type crdExampleEmbedInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCrdExampleEmbedInformer constructs a new informer for CrdExampleEmbed type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCrdExampleEmbedInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCrdExampleEmbedInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCrdExampleEmbedInformer constructs a new informer for CrdExampleEmbed type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCrdExampleEmbedInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdexampleV1().CrdExampleEmbeds(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdexampleV1().CrdExampleEmbeds(namespace).Watch(options)
			},
		},
		&crdexampleiov1.CrdExampleEmbed{},
		resyncPeriod,
		indexers,
	)
}

func (f *crdExampleEmbedInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCrdExampleEmbedInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *crdExampleEmbedInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdexampleiov1.CrdExampleEmbed{}, f.defaultInformer)
}

func (f *crdExampleEmbedInformer) Lister() v1.CrdExampleEmbedLister {
	return v1.NewCrdExampleEmbedLister(f.Informer().GetIndexer())
}
